name: Release
on:
  release:
    types: [published]
jobs:
  build_release:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: jimmysawczuk/power-monitor-web
          ref: master
          path: frontend
      - name: Set NPM Auth
        run: |
          echo '@fortawesome:registry=https://npm.fontawesome.com/' > ~/.npmrc
          echo '//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_AUTH_TOKEN }}' >> ~/.npmrc
      - name: Building frontend
        working-directory: frontend
        run: |
          yarn
          yarn build
      - name: Packaging static assets
        run: |
          go get -u github.com/jteeuwen/go-bindata/...
          go-bindata -o ./cmd/power-monitor/static.go -pkg main -prefix frontend/public frontend/public/...


