name: Release
on:
  release:
    types: [published]
  push:
    branches: [master]
jobs:
  build_release:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: jimmysawczuk/power-monitor-web
          ref: master
          path: frontend
      - name: Get tag
        id: tag
        uses: jimmysawczuk/actions/github/get-tag-from-ref@master
        with:
          ref: ${{ github.ref }}
      - name: Install tools
        run: |
          mkdir -p ~/bin
          export PATH=~/bin:$PATH

          wget -q https://github.com/jimmysawczuk/tmpl/releases/download/v2.0.0/tmpl-v2.0.0-linux-amd64
          mv tmpl-v2.0.0-linux-amd64 ~/bin/tmpl
          chmod +x ~/bin/tmpl

          wget -q https://github.com/jimmysawczuk/scm-status/releases/download/v2.2.0/scm-status-v2.2.0-linux-amd64
          mv scm-status-v2.2.0-linux-amd64 ~/bin/scm-status
          chmod +x ~/bin/scm-status

          which scm-status
          which tmpl

          go get -u github.com/jimmysawczuk/go-bindata/go-bindata
      - name: Set NPM Auth
        run: |
          echo '@fortawesome:registry=https://npm.fontawesome.com/' > ~/.npmrc
          echo '//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_AUTH_TOKEN }}' >> ~/.npmrc
      - name: Building frontend
        working-directory: frontend
        run: |
          yarn
          yarn build
      - name: Packaging static assets
        run: |
          go-bindata -o ./cmd/power-monitor/static.go -pkg main -prefix frontend/public frontend/public/...
      - name: Build binary
        run: |
          BUILDTAGS="-X main.version=$(scm-status | jq -r 'if .tags | length == 0 then "" else .tags[0] end') -X main.revision=$(scm-status | jq -r '.hex.short') -X main.date=$(date --iso-8601=seconds)"

          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
            go build -a -o power-monitor \
            -ldflags "-s -d -w $BUILDTAGS" \
            -mod=vendor \
            ./cmd/power-monitor

